version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: 490_project-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: 490_project-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:8000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

volumes:
  db_data:
